# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'appFirebase' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for appFirebase
  pod 'Firebase/Core', '~> 5.6.0'
  pod 'GoogleIDFASupport'

  target 'appFirebase-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  end

  target 'appFirebaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'appFirebase-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for appFirebase-tvOS

#   target 'appFirebase-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
